services:
  - type: web
    name: aldra-cms
    env: node
    region: frankfurt
    plan: free
    rootDir: aldra-cms
    buildCommand: npm install
    startCommand: npm run build && npm run start
    envVars:
      - key: NODE_ENV
      - key: PORT
      - key: DATABASE_CLIENT
      - key: DATABASE_URL
      - key: DATABASE_SCHEMA
        value: strapi
