/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/oversigt`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/onboarding_1`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/onboarding_2`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/onboarding_3`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/onboarding_4`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/onboarding_5`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/register`; params?: Router.UnknownInputParams; } | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/oversigt`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(tabs)'}/login` | `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/onboarding_1`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/onboarding_2`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/onboarding_3`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/onboarding_4`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/onboarding_5`; params?: Router.UnknownOutputParams; } | { pathname: `/onboarding/register`; params?: Router.UnknownOutputParams; } | { pathname: `/+not-found`, params: Router.UnknownOutputParams & {  } };
      href: Router.RelativePathString | Router.ExternalPathString | `/${`?${string}` | `#${string}` | ''}` | `/oversigt${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `${'/(tabs)'}/login${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/onboarding/onboarding_1${`?${string}` | `#${string}` | ''}` | `/onboarding/onboarding_2${`?${string}` | `#${string}` | ''}` | `/onboarding/onboarding_3${`?${string}` | `#${string}` | ''}` | `/onboarding/onboarding_4${`?${string}` | `#${string}` | ''}` | `/onboarding/onboarding_5${`?${string}` | `#${string}` | ''}` | `/onboarding/register${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/oversigt`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}` | `/`; params?: Router.UnknownInputParams; } | { pathname: `${'/(tabs)'}/login` | `/login`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/onboarding_1`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/onboarding_2`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/onboarding_3`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/onboarding_4`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/onboarding_5`; params?: Router.UnknownInputParams; } | { pathname: `/onboarding/register`; params?: Router.UnknownInputParams; } | `/+not-found` | { pathname: `/+not-found`, params: Router.UnknownInputParams & {  } };
    }
  }
}
